'use client'
import { useEffect,useState } from 'react'
import { useRouter } from 'next/navigation'
import { createClient } from '@/lib/supabase/client'
export default function Admin(){const router=useRouter();const [allowed,setAllowed]=useState<boolean|null>(null);const [profiles,setProfiles]=useState<any[]>([]);const [bookings,setBookings]=useState<any[]>([]);const [msg,setMsg]=useState('')
 async function load(){const s=createClient();const {data:{user}}=await s.auth.getUser();if(!user){router.push('/');return}const {data:me}=await s.from('profiles').select('*').eq('user_id',user.id).single();if(me?.role!=='admin'||me?.status!=='approved'){setAllowed(false);return}setAllowed(true);const [{data:p},{data:b}]=await Promise.all([s.from('profiles').select('*,villas(community,villa_number)').order('created_at',{ascending:false}),s.from('bookings').select('*,courts(display_name),villas(community,villa_number)').eq('status','active').order('starts_at')]);setProfiles(p||[]);const rows=[];for(const x of b||[]){const owner=(p||[]).find((q:any)=>q.user_id===x.user_id);rows.push({...x,owner})}setBookings(rows)}
 useEffect(()=>{load()},[])
 async function status(userId:string,status:'approved'|'rejected'|'suspended'){const s=createClient();const {error}=await s.rpc('admin_set_resident_status',{p_user_id:userId,p_status:status});setMsg(error?error.message:`Resident ${status}.`);await load()}
 async function cancel(id:string){const s=createClient();const {error}=await s.rpc('admin_cancel_booking',{p_booking_id:id});setMsg(error?error.message:'Booking cancelled.');await load()}
 if(allowed===null)return <main className="shell">Loading admin…</main>;if(!allowed)return <main className="shell"><div className="error">Admin access required.</div></main>
 return <main className="shell"><div className="topbar"><div><div className="brand">Mira Play Admin</div><div className="tag">Court and resident management</div></div><div className="nav"><a href="/dashboard">Resident view</a></div></div>{msg&&<div className="notice">{msg}</div>}<section className="card" style={{marginTop:16}}><h2>Residents</h2><div className="tableWrap"><table><thead><tr><th>Resident</th><th>Villa</th><th>Contact</th><th>Status</th><th>Action</th></tr></thead><tbody>{profiles.map(p=><tr key={p.user_id}><td>{p.first_name} {p.last_name}</td><td>{p.villas?`${p.villas.community} #${p.villas.villa_number}`:'—'}</td><td>{p.email}<br/>{p.mobile}</td><td>{p.status}</td><td><div className="row">{p.status==='pending'&&<><button className="btn" onClick={()=>status(p.user_id,'approved')}>Approve</button><button className="btn danger" onClick={()=>status(p.user_id,'rejected')}>Reject</button></>}{p.status==='approved'&&p.role!=='admin'&&<button className="btn danger" onClick={()=>status(p.user_id,'suspended')}>Suspend</button>}</div></td></tr>)}</tbody></table></div></section><section className="card" style={{marginTop:16}}><h2>Booked courts</h2><div className="tableWrap"><table><thead><tr><th>Court</th><th>Date / time</th><th>Resident / villa</th><th>Contact details</th><th></th></tr></thead><tbody>{bookings.map(b=><tr key={b.id}><td>{b.courts?.display_name}</td><td>{b.booking_date}<br/>{String(b.start_hour).padStart(2,'0')}:00 · {b.duration_hours}h</td><td>{b.owner?.first_name} {b.owner?.last_name}<br/>{b.villas?`${b.villas.community} #${b.villas.villa_number}`:''}</td><td>{b.owner?.email}<br/>{b.owner?.mobile}</td><td><button className="btn danger" onClick={()=>cancel(b.id)}>Cancel</button></td></tr>)}</tbody></table></div></section></main>}