'use client'
import { useEffect,useMemo,useState } from 'react'
import { useRouter } from 'next/navigation'
import { createClient } from '@/lib/supabase/client'
type Profile={user_id:string;first_name:string|null;last_name:string|null;email:string;mobile:string|null;status:string;role:string;villa_id:number|null;villas?:{community:string;villa_number:number}|null}
type Court={id:number;display_name:string}
type CourtRelation={display_name:string}\ntype Booking={id:string;booking_date:string;start_hour:number;duration_hours:number;starts_at:string;court_id:number;courts?:CourtRelation|CourtRelation[]|null}\nfunction courtName(c:Booking['courts']){return Array.isArray(c)?c[0]?.display_name:c?.display_name}
const hours=Array.from({length:15},(_,i)=>i+7)
function dstr(d:Date){return d.toISOString().slice(0,10)}
export default function Dashboard(){const router=useRouter();const [profile,setProfile]=useState<Profile|null>(null);const [courts,setCourts]=useState<Court[]>([]);const [bookings,setBookings]=useState<Booking[]>([]);const [busy,setBusy]=useState<{court_id:number;slot_start:string}[]>([]);const [date,setDate]=useState(dstr(new Date()));const [duration,setDuration]=useState(1);const [message,setMessage]=useState('');const [loading,setLoading]=useState(true)
 async function load(){const s=createClient();const {data:{user}}=await s.auth.getUser();if(!user){router.push('/');return}const {data:p}=await s.from('profiles').select('*, villas(community,villa_number)').eq('user_id',user.id).single();setProfile(p as Profile);if(p?.status==='approved'){const [{data:c},{data:b},{data:h}]=await Promise.all([s.from('courts').select('id,display_name').eq('active',true).order('sort_order'),s.from('bookings').select('id,booking_date,start_hour,duration_hours,starts_at,court_id,courts(display_name)').eq('user_id',user.id).eq('status','active').order('starts_at'),s.from('booking_hours').select('court_id,slot_start')]);setCourts((c||[]) as Court[]);setBookings((b||[]) as Booking[]);setBusy((h||[]) as any)}setLoading(false)}
 useEffect(()=>{load()},[])
 const busySet=useMemo(()=>new Set(busy.map(x=>{const d=new Date(x.slot_start);const parts=new Intl.DateTimeFormat('en-CA',{timeZone:'Asia/Dubai',year:'numeric',month:'2-digit',day:'2-digit',hour:'2-digit',hour12:false}).formatToParts(d);const get=(t:string)=>parts.find(p=>p.type===t)?.value||'';return `${x.court_id}|${get('year')}-${get('month')}-${get('day')}T${get('hour')}`})),[busy])
 function isBusy(c:number,h:number){const key=`${c}|${date}T${String(h).padStart(2,'0')}`;if(busySet.has(key))return true;if(duration===2)return busySet.has(`${c}|${date}T${String(h+1).padStart(2,'0')}`);return false}
 async function book(court:number,hour:number){setMessage('');const s=createClient();const {error}=await s.rpc('create_booking',{p_court_id:court,p_booking_date:date,p_start_hour:hour,p_duration_hours:duration});if(error){setMessage(error.message);return}setMessage('Booking confirmed.');await load()}
 async function cancel(id:string){const s=createClient();const {error}=await s.rpc('cancel_my_booking',{p_booking_id:id});setMessage(error?error.message:'Booking cancelled.');await load()}
 async function logout(){const s=createClient();await s.auth.signOut();router.push('/')}
 if(loading)return <main className="shell">Loading Mira Play…</main>;if(!profile)return <main className="shell"><div className="error">Profile unavailable.</div></main>
 const villa=(profile.villas as any)
 return <main className="shell"><div className="topbar"><div><div className="brand">Mira Play</div><div className="tag">{profile.first_name||'Resident'} · {villa?`${villa.community} · Villa ${villa.villa_number}`:''}</div></div><div className="nav">{profile.role==='admin'&&<a href="/admin">Admin</a>}<button onClick={logout}>Sign out</button></div></div>{profile.status!=='approved'?<div className="card"><h2>Registration {profile.status}</h2><p className="lead">Your villa registration must be approved before you can book a court.</p></div>:<><div className="grid3"><div className="card"><div className="muted">Active bookings</div><div className="stat">{bookings.length}/6</div></div><div className="card"><div className="muted">Booking length</div><div className="row" style={{marginTop:10}}><button className={`btn ${duration===1?'':'secondary'}`} onClick={()=>setDuration(1)}>1 hour</button><button className={`btn ${duration===2?'':'secondary'}`} onClick={()=>setDuration(2)}>2 hours</button></div></div><div className="card"><div className="muted">Choose date</div><input style={{marginTop:10,padding:10,border:'1px solid var(--line)',borderRadius:10}} type="date" value={date} onChange={e=>setDate(e.target.value)}/></div></div>{message&&<div className={message.includes('confirmed')||message.includes('cancelled')?'notice':'error'} style={{marginTop:16}}>{message}</div>}<section className="card" style={{marginTop:16}}><h2>Book a court</h2><p className="muted">Select any available start time. A 2-hour booking automatically occupies two consecutive hours.</p><div className="courtGrid">{courts.map(c=><div key={c.id} className="card" style={{boxShadow:'none'}}><strong>{c.display_name}</strong><div className="stack" style={{marginTop:12}}>{hours.filter(h=>duration===1||h<=20).map(h=>{const b=isBusy(c.id,h);return <button key={h} disabled={b} className={`slot ${b?'busy':''}`} onClick={()=>book(c.id,h)}>{String(h).padStart(2,'0')}:00 · {b?'Booked':'Available'}</button>})}</div></div>)}</div></section><section className="card" style={{marginTop:16}}><h2>My bookings</h2>{bookings.length===0?<p className="muted">No active bookings.</p>:bookings.map(b=><div className="booking" key={b.id}><div><strong>{courtName(b.courts)||`Court ${b.court_id}`}</strong><div className="muted">{b.booking_date} · {String(b.start_hour).padStart(2,'0')}:00 · {b.duration_hours} hour{b.duration_hours>1?'s':''}</div></div><button className="btn danger" onClick={()=>cancel(b.id)}>Cancel</button></div>)}</section></>}</main>}