'use client'
import { FormEvent,useEffect,useMemo,useState } from 'react'
import { useRouter } from 'next/navigation'
import { Brand } from '@/components/Branding'
import { createClient } from '@/lib/supabase/client'
type Profile={user_id:string;first_name:string|null;last_name:string|null;email:string;mobile:string|null;status:string;role:string;villas?:{community:string;villa_number:number}|null}
type Court={id:number;display_name:string}
type Booking={id:string;duration_hours:number;starts_at:string;ends_at:string;status:string;court_id:number;courts?:{display_name:string}|{display_name:string}[]|null}
type News={id:string;title:string;body:string}
type Busy={court_id:number;slot_start:string}
const hours=Array.from({length:15},(_,i)=>i+7)
function courtName(c:Booking['courts']){return Array.isArray(c)?c[0]?.display_name:c?.display_name}
function dubaiNow(){const p=new Intl.DateTimeFormat('en-CA',{timeZone:'Asia/Dubai',year:'numeric',month:'2-digit',day:'2-digit',hour:'2-digit',hour12:false}).formatToParts(new Date());const g=(t:string)=>p.find(x=>x.type===t)?.value||'';return {date:`${g('year')}-${g('month')}-${g('day')}`,hour:Number(g('hour'))}}
function fmt(v:string){return new Intl.DateTimeFormat('en-GB',{timeZone:'Asia/Dubai',day:'numeric',month:'short',year:'numeric',hour:'2-digit',minute:'2-digit',hour12:false}).format(new Date(v))}
export default function Dashboard(){const router=useRouter();const [tab,setTab]=useState<'home'|'book'|'bookings'|'profile'>('home');const [profile,setProfile]=useState<Profile|null>(null);const [courts,setCourts]=useState<Court[]>([]);const [bookings,setBookings]=useState<Booking[]>([]);const [busy,setBusy]=useState<Busy[]>([]);const [news,setNews]=useState<News[]>([]);const [date,setDate]=useState(dubaiNow().date);const [court,setCourt]=useState<number|''>('');const [duration,setDuration]=useState(1);const [pending,setPending]=useState<{court:number;name:string;hour:number}|null>(null);const [message,setMessage]=useState('');const [loading,setLoading]=useState(true)
async function load(){const s=createClient();const {data:{user}}=await s.auth.getUser();if(!user){router.push('/');return}const {data:p}=await s.from('profiles').select('*,villas(community,villa_number)').eq('user_id',user.id).single();setProfile(p as Profile);if(p?.status==='approved'){const [{data:c},{data:b},{data:h},{data:n}]=await Promise.all([s.from('courts').select('id,display_name').eq('active',true).order('sort_order'),s.from('bookings').select('id,duration_hours,starts_at,ends_at,status,court_id,courts(display_name)').eq('user_id',user.id).order('starts_at',{ascending:false}),s.from('booking_hours').select('court_id,slot_start'),s.from('news_updates').select('id,title,body').eq('published',true).order('published_at',{ascending:false}).limit(5)]);const cs=(c||[]) as Court[];setCourts(cs);if(court===''&&cs.length)setCourt(cs[0].id);setBookings((b||[]) as Booking[]);setBusy((h||[]) as Busy[]);setNews((n||[]) as News[])}setLoading(false)}
useEffect(()=>{load()},[])
const busySet=useMemo(()=>new Set(busy.map(x=>{const d=new Date(x.slot_start);const p=new Intl.DateTimeFormat('en-CA',{timeZone:'Asia/Dubai',year:'numeric',month:'2-digit',day:'2-digit',hour:'2-digit',hour12:false}).formatToParts(d);const g=(t:string)=>p.find(y=>y.type===t)?.value||'';return `${x.court_id}|${g('year')}-${g('month')}-${g('day')}T${g('hour')}`})),[busy])
const now=Date.now(),future=bookings.filter(b=>b.status==='active'&&+new Date(b.starts_at)>now).sort((a,b)=>+new Date(a.starts_at)-+new Date(b.starts_at)),active=bookings.filter(b=>b.status==='active'&&+new Date(b.starts_at)<=now&&+new Date(b.ends_at)>now),past=bookings.filter(b=>b.status==='cancelled'||+new Date(b.ends_at)<=now)
function isPast(h:number){const n=dubaiNow();return date<n.date||(date===n.date&&h<=n.hour)}
function isBusy(id:number,h:number){if(busySet.has(`${id}|${date}T${String(h).padStart(2,'0')}`))return true;return duration===2&&busySet.has(`${id}|${date}T${String(h+1).padStart(2,'0')}`)}
async function confirm(){if(!pending)return;const s=createClient();const {error}=await s.rpc('create_booking',{p_court_id:pending.court,p_booking_date:date,p_start_hour:pending.hour,p_duration_hours:duration});if(error){setMessage(error.message);setPending(null);return}setMessage('Booking confirmed.');setPending(null);await load();setTab('bookings')}
async function cancel(id:string){const s=createClient();const {error}=await s.rpc('cancel_my_booking',{p_booking_id:id});setMessage(error?error.message:'Booking cancelled.');await load()}
async function saveProfile(e:FormEvent<HTMLFormElement>){e.preventDefault();if(!profile)return;const f=new FormData(e.currentTarget);const s=createClient();const {error}=await s.from('profiles').update({first_name:String(f.get('first_name')),last_name:String(f.get('last_name')),mobile:String(f.get('mobile'))}).eq('user_id',profile.user_id);setMessage(error?error.message:'Profile updated.');if(!error)await load()}
async function resetPassword(){if(!profile)return;const s=createClient();const {error}=await s.auth.resetPasswordForEmail(profile.email,{redirectTo:`${location.origin}/reset-password`});setMessage(error?error.message:'Password reset email sent.')}
async function logout(){const s=createClient();await s.auth.signOut();router.push('/')}
if(loading)return <main className="shell">Loading Mira Play…</main>;if(!profile)return <main className="shell"><div className="error">Profile unavailable.</div></main>;const villa=profile.villas as any;if(profile.status!=='approved')return <main className="shell"><Brand/><div className="card" style={{marginTop:24}}><h2>Registration {profile.status}</h2><p className="muted">Admin approval is required before booking.</p></div></main>
return <main className="shell"><div className="topbar"><div><Brand/><div className="tag">{profile.first_name||'Resident'} · {villa?`${villa.community} · Villa ${villa.villa_number}`:''}</div></div><div className="nav">{profile.role==='admin'&&<a href="/admin">Admin</a>}<button onClick={logout}>Sign out</button></div></div><div className="tabbar"><button className={tab==='home'?'active':''} onClick={()=>setTab('home')}>Home</button><button className={tab==='book'?'active':''} onClick={()=>setTab('book')}>Book</button><button className={tab==='bookings'?'active':''} onClick={()=>setTab('bookings')}>My bookings</button><button className={tab==='profile'?'active':''} onClick={()=>setTab('profile')}>Profile</button></div>{message&&<div className={/confirmed|cancelled|updated|sent/.test(message)?'notice':'error'} style={{marginBottom:16}}>{message}</div>}
{tab==='home'&&<><div className="grid3"><div className="card"><div className="muted">Future</div><div className="stat">{future.length}</div></div><div className="card"><div className="muted">Active now</div><div className="stat">{active.length}</div></div><div className="card"><div className="muted">Past</div><div className="stat">{past.length}</div></div></div><div className="grid2" style={{marginTop:16}}><section className="card"><h2>Next booking</h2>{future[0]?<BookingRow b={future[0]} cancel={cancel}/>:<p className="muted">No upcoming booking.</p>}</section><section className="card"><h2>News & updates</h2>{news.length?news.map(n=><article className="newsItem" key={n.id}><strong>{n.title}</strong><p>{n.body}</p></article>):<p className="muted">No updates right now.</p>}</section></div></>}
{tab==='book'&&<section className="card"><h2>Book a court</h2><div className="grid3"><div className="field"><label>Date</label><input type="date" min={dubaiNow().date} value={date} onChange={e=>setDate(e.target.value)}/></div><div className="field"><label>Court</label><select value={court} onChange={e=>setCourt(Number(e.target.value))}>{courts.map(c=><option key={c.id} value={c.id}>{c.display_name}</option>)}</select></div><div className="field"><label>Duration</label><select value={duration} onChange={e=>setDuration(Number(e.target.value))}><option value={1}>1 hour</option><option value={2}>2 hours</option></select></div></div>{court!==''&&(()=>{const c=courts.find(x=>x.id===court);if(!c)return null;return <div className="slotGrid">{hours.filter(h=>duration===1||h<=20).map(h=>{const p=isPast(h),b=isBusy(c.id,h),off=p||b;return <button key={h} disabled={off} className={`slot ${off?'busy':''}`} onClick={()=>setPending({court:c.id,name:c.display_name,hour:h})}>{String(h).padStart(2,'0')}:00<span>{p?'Past':b?'Unavailable':'Available'}</span></button>})}</div>})()}</section>}
{tab==='bookings'&&<div className="stack"><BookingGroup title="Future" items={future} cancel={cancel}/><BookingGroup title="Active now" items={active}/><BookingGroup title="Past & cancelled" items={past}/></div>}
{tab==='profile'&&<div className="grid2"><form className="card stack" onSubmit={saveProfile}><h2>Profile</h2><div className="grid2"><div className="field"><label>First name</label><input name="first_name" defaultValue={profile.first_name||''}/></div><div className="field"><label>Last name</label><input name="last_name" defaultValue={profile.last_name||''}/></div></div><div className="field"><label>Email</label><input value={profile.email} disabled/></div><div className="field"><label>Mobile</label><input name="mobile" defaultValue={profile.mobile||''}/></div><div className="field"><label>Villa</label><input value={villa?`${villa.community} · Villa ${villa.villa_number}`:'—'} disabled/></div><button className="btn">Save profile</button></form><div className="card stack"><h2>Account & security</h2><button className="btn secondary" onClick={resetPassword}>Send password reset email</button><a href="/terms">Terms & Conditions</a></div></div>}
{pending&&<div className="modalBackdrop"><div className="card modalCard stack"><h2>Confirm booking</h2><div className="summaryRow"><span>Court</span><strong>{pending.name}</strong></div><div className="summaryRow"><span>Date</span><strong>{date}</strong></div><div className="summaryRow"><span>Time</span><strong>{String(pending.hour).padStart(2,'0')}:00 – {String(pending.hour+duration).padStart(2,'0')}:00</strong></div><div className="summaryRow"><span>Duration</span><strong>{duration} hour{duration>1?'s':''}</strong></div><div className="row" style={{justifyContent:'flex-end'}}><button className="btn secondary" onClick={()=>setPending(null)}>Cancel</button><button className="btn" onClick={confirm}>Confirm booking</button></div></div></div>}</main>}
function BookingGroup({title,items,cancel}:{title:string;items:Booking[];cancel?:(id:string)=>void}){return <section className="card"><div className="sectionHead"><h2>{title}</h2><span className="pill">{items.length}</span></div>{items.length?items.slice(0,20).map(b=><BookingRow key={b.id} b={b} cancel={cancel}/>):<p className="muted">None.</p>}</section>}
function BookingRow({b,cancel}:{b:Booking;cancel?:(id:string)=>void}){return <div className="booking"><div><strong>{courtName(b.courts)||`Court ${b.court_id}`}</strong><div className="muted">{fmt(b.starts_at)} · {b.duration_hours}h</div>{b.status==='cancelled'&&<span className="tag">Cancelled</span>}</div>{cancel&&b.status==='active'&&+new Date(b.starts_at)>Date.now()&&<button className="btn danger" onClick={()=>cancel(b.id)}>Cancel</button>}</div>}
